SetTitleMatchMode 3
!1::ControlSend "{1 down}{1 up}",,"PNGTuberPlus"
!2::ControlSend "{2 down}{2 up}",,"PNGTuberPlus"
!3::ControlSend "{3 down}{3 up}",,"PNGTuberPlus"
!4::ControlSend "{4 down}{4 up}",,"PNGTuberPlus"
!5::ControlSend "{5 down}{5 up}",,"PNGTuberPlus"
!6::ControlSend "{6 down}{6 up}",,"PNGTuberPlus"
!7::ControlSend "{7 down}{7 up}",,"PNGTuberPlus"
!8::ControlSend "{8 down}{8 up}",,"PNGTuberPlus"
!9::ControlSend "{9 down}{9 up}",,"PNGTuberPlus"
!0::ControlSend "{0 down}{0 up}",,"PNGTuberPlus"